host: "127.0.0.1"
port: 8080

api_key: "your-api-key"

data_directory: "/path/to/data"
ocserv_passwd_path: "/path/to/ocserv/passwd"

organization: "Your Organization"
ca_certificate_path: "/path/to/ca.crt"
ca_private_key_path: "/path/to/ca.key"
client_private_key_path: "/path/to/client.key"